name: home-server

include:
  - compose-beszel.yml
  - compose-freshrss.yml
  - compose-homeassistant.yml
  - compose-homepage.yml
  - compose-linkding.yml
  - compose-proxy.yml
  - compose-scrutiny.yml
  - compose-spaceweather.yml
  - compose-technitium.yml
  - compose-torrent.yml
  - compose-backup.yml

networks:
  frontend:
  backend:
